---
kind: pipeline
name: build-image

steps:
- name: notify
  image: plugins/slack
  settings:
    channel: sandbox
    username: drone
    webhook:
      from_secret: slack_webhook

trigger:
  branch:
  - master