---
kind: pipeline
name: build

steps:
- name: notify
  image: plugins/slack
  settings:
    channel: sandbox
    username: drone
    webhook:
      from_secret: slack_webhook
  template: >
    hello

trigger:
  branch:
  - master